name: ${name}
version: ${version}
description: ${description}
load: POSTWORLD
api-version: ${api}
author: Hugo B.

main: ${group}.${artifact}.${main}

permissions:
  # main command
  perm.use:
    description: Allows you to edit the text on Signs
    default: op